# Generated by Django 6.0.7 on 2026-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arithmetic_accuracy', models.FloatField(default=0)),
                ('verbal_accuracy', models.FloatField(default=0)),
                ('reasoning_accuracy', models.FloatField(default=0)),
                ('coding_accuracy', models.FloatField(default=0)),
                ('weak_areas', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
