# Generated by Django 6.0.7 on 2026-07-19 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalytics',
            name='exam_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
