# Generated by Django 6.0.7 on 2026-08-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic_slug', models.CharField(max_length=100)),
                ('chapter_title', models.CharField(default='General Notes', max_length=255)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('vector_json', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic_slug', models.CharField(max_length=100)),
                ('cognitive_state', models.CharField(max_length=50)),
                ('wpm', models.FloatField(default=0.0)),
                ('backspace_count', models.IntegerField(default=0)),
                ('pause_duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBKTTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic_slug', models.CharField(max_length=100)),
                ('mastery_probability', models.FloatField(default=0.1)),
                ('last_reviewed_at', models.DateTimeField(auto_now=True)),
                ('review_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject', 'topic_slug')},
            },
        ),
    ]
