# Generated by Django 6.0.7 on 2026-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='section_type',
            field=models.CharField(max_length=100),
        ),
    ]
