# Generated by Django 6.0.7 on 2026-07-27 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('hr', 'HR Interview'), ('jam', 'JAM (Just A Minute)'), ('gd', 'Group Discussion'), ('custom', 'Custom')], default='hr', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional hint or context for the topic')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpeechAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_topic', models.CharField(blank=True, max_length=300)),
                ('transcript', models.TextField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('wpm', models.FloatField(default=0)),
                ('grammar_score', models.FloatField(default=0)),
                ('fluency_score', models.FloatField(default=0)),
                ('vocabulary_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('filler_count', models.IntegerField(default=0)),
                ('filler_words_found', models.JSONField(default=list)),
                ('corrected_transcript', models.TextField(blank=True)),
                ('grammar_errors', models.JSONField(default=list)),
                ('vocabulary_upgrades', models.JSONField(default=list)),
                ('tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_attempts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.speechtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
