# Generated by Django 6.0.7 on 2026-08-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_aptitudetopic_javatopic_aptitudequestion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraptitudeprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useraptitudeprogress',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='useraptitudeprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AptitudeQuestion',
        ),
        migrations.DeleteModel(
            name='AptitudeTopic',
        ),
        migrations.DeleteModel(
            name='UserAptitudeProgress',
        ),
    ]
