# Generated by Django 6.0.7 on 2026-07-19 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('fullscreen_exit', 'Fullscreen Exit'), ('tab_switch', 'Tab Switch'), ('right_click', 'Right Click Attempt'), ('keyboard_shortcut', 'Keyboard Shortcut'), ('copy_paste', 'Copy/Paste Attempt')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
